apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

bases:
- ../../helm-charts/trino/

# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: giro

resources:
- all.yaml
# - nginx-deployment.yaml
# - configMap.yaml
# - nginx-service.yaml

# resources:
# - ../../base

# images:
# - name: prod-app
#   newTag: 1.23.4
