apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

# bases:
# - ../base/

# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: giro

resources:
- nginx-configmap.yaml
- nginx-deployment.yaml
- configMap.yaml
- nginx-service.yaml
